#! /bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
	upgrade|install-upgrade)
		;;
	abort-upgrade)
		exit 0
		;;
esac

#
# Add the "tklbam-proxy" user/group to /etc/passwd if needed.
#

if ! grep -q "^proxy:" /etc/passwd
then
	#
	#	Let's hope that this works; if /var/spool/squid is
	#	already present this fails :(
	#
	adduser --system --home /var/spool/tklbam-squid --group tklbam-proxy
	#
	# Change the shell so that cron jobs will work.
	# (They run as root now, but you can never know).
	#
	chsh -s /bin/sh tklbam-proxy
fi

exit 0
